## Self-Assessment
Our project was Pricing Transparency in Healthcare.  We identified pricing data sets available on public websites to download in order to compare healthcare pricing with quality.
My biggest concern during the project was the machine learning element.  While this topic is of great interest, my only experience has been during the last two modules of this bootcamp.  I felt like I ran into constant issues, but my team along with the teaching assistants and instructor provided some much-needed guidance.  Our project data set end up with over a million rows and was too large to run through Python without timing out and freezing up.  We also concluded that our focus needed to be narrowed to get any useful information from machine learning.  Even when narrowing, we found that the data elements did not have the correlation that we were expecting (between cost and quality).
## Team Assessment 
Our team split up the initial data gathering and cleaning.  There were twenty top ten hospitals identified for our data set, and we split them into four groups of five.  For the next phases of the project, we split the work up by team member interest and skill.  One member took on compiling the data sets, another took on cleaning techniques with Python, another Tableau vizulations, and I took on the machine learning element.
Even though we split up different aspects of the workload, we stayed in close communication and kept one another apprised and involved with each step.  Since we all work for the same employer, we were able to utilize an internal Team channel to stay connected.  While off work, we stay connected via Zoom or Slack.  We each provided feedback and direction to problem solve issues along the way.
While we were able to do draw a fair number of conclusions from our initial hypothesis, it would be more useful to break the data elements down into smaller subcategories for further analysis.  
## Project Summary
Working in healthcare, this topic is of great interest.  It was a great experience to work with other interested parties and be able to split up the workload to take this on.  While the overreaching conclusions fell a little short of expectations, there is a data set that will be useful for future analysis.  There will also more to come as insurance companies are schedule to release their pricing to the public in July 2022.
We were able to conclude that pricing is higher in major metropolitan areas, hospitals are generally located in areas of notably higher population and income.  Pricing among payor groups is inconsistent.  Federal pricing transparency requirements are not being met by all hospitals, data is either missing or difficult to work with.  There is no obvious correlation between quality and pricing in healthcare.
